function disp(orien)
arguments (Input)
	orien (:,1) Orien
end
if isempty(orien)
	fprintf("Empty Orientation\n");
elseif isvector(orien)
	for i = 1:numel(orien)
		if isempty(orien(i).ref)
			fprintf( ...
				"Orientation obtained with a \'%s\' sequence of angles " + ...
				"<%g %g %g> deg in empty Frame\n", ...
				orien(i).seqID, ...
				rad2deg(orien(i).angles));
		else
			fprintf( ...
				"Orientation obtained with a \'%s\' sequence of angles " + ...
				"<%g %g %g> deg in \'%s\' Frame\n", ...
				orien(i).seqID, ...
				rad2deg(orien(i).angles), ...
				orien(i).ref.uID);
		end
	end
end
end