classdef FrameHierarchyFixture < matlab.unittest.fixtures.Fixture
	% FrameHierarchyFixture - Shared test fixture for frame hierarchies
	%
	% This fixture creates a unified frame hierarchy that can be reused
	% across multiple test classes:
	%
	%    World
	%    ├── fr1 (Frame1) at [1;1;1]
	%    │   ├── fr2a (Frame2a) at [2;0;0] from fr1
	%    │   │   └── fr3a (Frame3a) at origin, rotated π/2 about Z
	%    │   ├── fr2b (Frame2b) at [0;2;0] from fr1
	%    │   │   └── fr3b (Frame3b) at origin, rotated π/2 about Y
	%    │   └── fr2c (Frame2c) at [0;0;2] from fr1
	%    │       └── fr3c (Frame3c) at origin, rotated π/2 about X
	%    ├── fr2 at origin
	%    └── fr3 at [3;3;3]
	%        ├── fr4 at origin, rotated π/2 about X
	%        ├── fr5 at origin, rotated π/2 about Y
	%        └── fr6 at origin, rotated π/2 about Z
	%
	% Usage:
	%   In your test class, define a property and apply the fixture:
	%
	%   properties
	%       frameFixture
	%   end
	%
	%   methods (TestClassSetup)
	%       function setupFrames(testCase)
	%           testCase.frameFixture = testCase.applyFixture(...
	%               FrameHierarchyFixture());
	%       end
	%   end
	%
	%   Then access frames via: testCase.frameFixture.world, 
	%                          testCase.frameFixture.fr1, etc.
	
	properties
		world
		% Frames from both hierarchies
		fr1    % Also known as Frame1
		fr2    % Simple frame at origin
		fr3    % Simple frame at [3;3;3]
		fr2a   % Also known as Frame2a
		fr2b   % Also known as Frame2b
		fr2c   % Also known as Frame2c
		fr3a   % Also known as Frame3a
		fr3b   % Also known as Frame3b
		fr3c   % Also known as Frame3c
		fr4    % Child of fr3, rotated about X
		fr5    % Child of fr3, rotated about Y
		fr6    % Child of fr3, rotated about Z
	end
	
	methods
		function setup(fixture)
			% Create World and the unified frame hierarchy
			fixture.world = World.getWorld();
			
			% Create fr1 branch with tree structure (originally from testPoint)
			fixture.fr1 = Frame("Frame1", ...
				Point([1; 1; 1], fixture.world), ...
				Orien([0; 0; 0], "321", fixture.world), ...
				fixture.world);
			
			fixture.fr2a = Frame("Frame2a", ...
				Point([2; 0; 0], fixture.fr1), ...
				Orien([0; 0; 0], "321", fixture.fr1), ...
				fixture.fr1);
			fixture.fr2b = Frame("Frame2b", ...
				Point([0; 2; 0], fixture.fr1), ...
				Orien([0; 0; 0], "321", fixture.fr1), ...
				fixture.fr1);
			fixture.fr2c = Frame("Frame2c", ...
				Point([0; 0; 2], fixture.fr1), ...
				Orien([0; 0; 0], "321", fixture.fr1), ...
				fixture.fr1);
			
			fixture.fr3a = Frame("Frame3a", ...
				Point([0; 0; 0], fixture.fr2a), ...
				Orien([0; 0; pi/2], "321", fixture.fr2a), ...
				fixture.fr2a);
			fixture.fr3b = Frame("Frame3b", ...
				Point([0; 0; 0], fixture.fr2b), ...
				Orien([0; pi/2; 0], "321", fixture.fr2b), ...
				fixture.fr2b);
			fixture.fr3c = Frame("Frame3c", ...
				Point([0; 0; 0], fixture.fr2c), ...
				Orien([pi/2; 0; 0], "321", fixture.fr2c), ...
				fixture.fr2c);
			
			% Create simple frames (originally from testFrame)
			fixture.fr2 = Frame("fr2", ...
				Point([0; 0; 0], fixture.world), ...
				Orien([0; 0; 0], "321", fixture.world), ...
				fixture.world);
			fixture.fr3 = Frame("fr3", ...
				Point([3; 3; 3], fixture.world), ...
				Orien([0; 0; 0], "321", fixture.world), ...
				fixture.world);
			fixture.fr4 = Frame("fr4", ...
				Point([0; 0; 0], fixture.fr3), ...
				Orien([pi/2; 0; 0], "321", fixture.fr3), ...
				fixture.fr3);
			fixture.fr5 = Frame("fr5", ...
				Point([0; 0; 0], fixture.fr3), ...
				Orien([0; pi/2; 0], "321", fixture.fr3), ...
				fixture.fr3);
			fixture.fr6 = Frame("fr6", ...
				Point([0; 0; 0], fixture.fr3), ...
				Orien([0; 0; pi/2], "321", fixture.fr3), ...
				fixture.fr3);

			fixture.addTeardown(@clear, "World", "getWorld")
		end

	end
end
