classdef testVector < matlab.unittest.TestCase

	properties
	
		world, fr0, fr1, fr2, fr3, v0, v3
	
	end

	methods (TestClassSetup)

		function addClassToPath(testCase)
			testCase.applyFixture( ...
				matlab.unittest.fixtures.PathFixture(".."));
			testCase.applyFixture( ...
				matlab.unittest.fixtures.PathFixture("../includes/TreeNode"));
		end
		
	end
	
	methods (TestMethodSetup)

		function createWorldFrame(testCase)

			testCase.world = World.getWorld();

			testCase.fr0 = Frame("Frame1", ...
				Point([1; 1; 1], testCase.world), ...
				Orien([0; 0; 0], "321", testCase.world), ...
				testCase.world);
			testCase.fr3 = Frame("Frame3", ...
				Point([0; 0; 0], testCase.fr0), ...
				Orien([pi/2; 0; 0], "321", testCase.fr0), ...
				testCase.fr0);
			testCase.fr2 = Frame("Frame2", ...
				Point([0; 0; 0], testCase.fr0), ...
				Orien([0; pi/2; 0], "321", testCase.fr0), ...
				testCase.fr0);
			testCase.fr1 = Frame("Frame1", ...
				Point([0; 0; 0], testCase.fr0), ...
				Orien([0; 0; pi/2], "321", testCase.fr0), ...
				testCase.fr0);

			testCase.v0 = Vector([1; 0; 0], testCase.fr0);
			testCase.v3 = Vector([1; 0; 0], testCase.fr3);

			testCase.addTeardown(@clear, "World", "getWorld")
		end

	end

	%%
	methods (Test)

		function testCreateArrayOfVectors(testCase)
			numVectors = 5;
			vectorsArray = Vector.empty(numVectors,0);
			for i = 1:numVectors
				vectorsArray(i) = Vector(rand(3,1), testCase.world);
			end
			testCase.verifyEqual(length(vectorsArray), numVectors);

			vectorsArrayDefault(5) = Vector(rand(3,1), testCase.world);
			testCase.verifyEqual(vectorsArrayDefault(1).coords, [0; 0; 0])
			testCase.verifyEqual( ...
				vectorsArrayDefault(1).ref.uID, ...
				"World")
			testCase.verifyEqual( ...
				vectorsArrayDefault(2).ref.uID, ...
				"World")
		end


		function viewIn(testCase)
			testCase.verifyEqual( ...
				testCase.v0.resolveIn(testCase.fr0).coords, ...
				[1; 0; 0]);
			testCase.verifyEqual( ...
				testCase.v0.resolveIn(testCase.fr3).coords, ...
				[0; -1; 0]);
			testCase.verifyEqual( ...
				testCase.v0.resolveIn(testCase.fr2).coords, ...
				[0; 0; 1]);
			testCase.verifyEqual( ...
				testCase.v0.resolveIn(testCase.fr1).coords, ...
				[1; 0; 0]);
			testCase.verifyEqual( ...
				testCase.v3.resolveIn(testCase.world).coords, ...
				[0; 1; 0]);
		end

		
		function testRotate(testCase)
			testCase.verifyEqual( ...
				testCase.v0.rotate( ...
				Orien([pi/2; 0; 0], "321", testCase.fr0)).coords, ...
				[0; 1; 0]);
			testCase.verifyEqual( ...
				testCase.v0.rotate( ...
				Orien([0; pi/2; 0], "321", testCase.fr0)).coords, ...
				[0; 0; -1]);
			testCase.verifyEqual( ...
				testCase.v0.rotate( ...
				Orien([0; 0; pi/2], "321", testCase.fr0)).coords, ...
				[1; 0; 0]);
		end

	end

end