classdef testVector < matlab.unittest.TestCase

	properties
	
		world, fr0, fr1, fr2, fr3, v0, v3
	
	end

	methods (TestClassSetup)

		function addClassToPath(testCase)
			testCase.applyFixture( ...
				matlab.unittest.fixtures.PathFixture(".."));
			testCase.applyFixture( ...
				matlab.unittest.fixtures.PathFixture("../includes/TreeNode"));
		end
		
	end
	
	methods (TestMethodSetup)

		function createWorldFrame(testCase)

			testCase.world = World.getWorld();

			testCase.fr0 = Frame("Frame1", ...
				[1, 1, 1], [0, 0, 0], "321", testCase.world);
			testCase.fr3 = Frame("Frame3", ...
				[0, 0, 0], [pi/2, 0, 0], "321", testCase.fr0);
			testCase.fr2 = Frame("Frame2", ...
				[0, 0, 0], [0, pi/2, 0], "321", testCase.fr0);
			testCase.fr1 = Frame("Frame1", ...
				[0, 0, 0], [0, 0, pi/2], "321", testCase.fr0);

			testCase.v0 = Vector([1 0 0], testCase.fr0);
			testCase.v3 = Vector([1 0 0], testCase.fr3);

			testCase.addTeardown(@clear, "World", "getWorld")
		end

	end

	%%
	methods (Test)

		function viewIn(testCase)
			testCase.verifyEqual( ...
				testCase.v0.viewIn(testCase.fr0), ...
				[1; 0; 0]);
			testCase.verifyEqual( ...
				testCase.v0.viewIn(testCase.fr3), ...
				[0; -1; 0]);
			testCase.verifyEqual( ...
				testCase.v0.viewIn(testCase.fr2), ...
				[0; 0; 1]);
			testCase.verifyEqual( ...
				testCase.v0.viewIn(testCase.fr1), ...
				[1; 0; 0]);
			testCase.verifyEqual( ...
				testCase.v3.viewIn(testCase.world), ...
				[0; 1; 0]);
		end

		function testRotate(testCase)
			testCase.verifyEqual( ...
				testCase.v0.calcRotate( ...
				Orien([pi/2 0 0], "321", testCase.fr0)), ...
				[0; 1 ;0]);
			testCase.verifyEqual( ...
				testCase.v0.calcRotate( ...
				Orien([0 pi/2 0], "321", testCase.fr0)), ...
				[0; 0; -1]);
			testCase.verifyEqual( ...
				testCase.v0.calcRotate( ...
				Orien([0 0 pi/2], "321", testCase.fr0)), ...
				[1; 0; 0]);
		end

	end

end