function disp(vec)
arguments (Input)
	vec (:,1) Vector
end
if isempty(vec)
	fprintf("Empty Vector\n");
else
	for i = 1:numel(vec)
		exyz = isempty(vec(i).coords);
		ewrt = isempty(vec(i).ref);
		if exyz & ewrt
			fprintf( ...
				"Vector with empty comps " + ...
				"in empty Frame\n");
		elseif exyz
			fprintf( ...
				"Vector with empty comps " + ...
				"in Frame: '%s'\n", ...
				vec(i).ref.name);
		elseif ewrt
			fprintf( ...
				"Vector with coordinates: [%g %g %g] " + ...
				"in empty Frame\n", ...
				vec(i).coords);
		else
			fprintf( ...
				"Vector with coordinates: [%g %g %g] " + ...
				"in Frame: '%s'\n", ...
				vec(i).coords, ...
				vec(i).ref.name);
		end
	end
end
end