function point = rotate(point, orien, p0)
% Rotate point about another point p0, according to the orientation
% orien. All geomObjects have to be resolved in the same frame.
arguments (Input)
	point (1,1) Point
	orien (1,1) Orien
	p0 (1,1) Point
end
arguments (Output)
	point (1,1) Point
end
assert( ...
	point.ref == p0.ref, ...
	"Point:rotate:sameRef", ...
	"Point and center of rotation must be expressed in " + ...
	"the same ref frame")
assert( ...
	point.ref == orien.ref, ...
	"Point:rotate:sameRef", ...
	"Point and orientation must be expressed in " + ...
	"the same ref frame")
point.coords =  p0.coords + orien.coords * (point.coords - p0.coords);
end